# Generated by Django 3.2.25 on 2025-09-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.department', verbose_name='Отдел-исполнитель'),
        ),
    ]
